"""The values module contains enums for the months, parshios, and holidays.
These are used throughout the codebase to refer to these values in a
consistent way.
"""

from enum import Enum


class Months(Enum):
    NISSAN = 'ניסן'
    IYAR = 'אייר'
    SIVAN = 'סיון'
    TAMMUZ = 'תמוז'
    AV = 'אב'
    ELUL = 'אלול'
    TISHREI = 'תשרי'
    CHESHVAN = 'חשון'
    KISLEV = 'כסלו'
    TEVES = 'טבת'
    SHEVAT = 'שבט'
    ADAR = 'אדר'
    ADAR1 = 'אדר א׳'
    ADAR2 = 'אדר ב׳'


class Parshios(Enum):
    BEREISHIS = 'בראשית'
    NOACH = 'נח'
    LECH_LECHA = 'לך לך'
    VAYEIRA = 'וירא'
    CHAYEI_SARAH = 'חיי שרה'
    TOLDOS = 'תולדות'
    VAYEITZEI = 'ויצא'
    VAYISHLACH = 'וישלח'
    VAYEISHEV = 'וישב'
    MIKEITZ = 'מקץ'
    VAYIGASH = 'ויגש'
    VAYECHI = 'ויחי'
    SHEMOS = 'שמות'
    VAEIRA = 'וארא'
    BO = 'בא'
    BESHALACH = 'בשלח'
    YISRO = 'יתרו'
    MISHPATIM = 'משפטים'
    TERUMAH = 'תרומה'
    TETZAVEH = 'תצוה'
    KI_SISA = 'כי תשא'
    VAYAKHEL = 'ויקהל'
    PEKUDEI = 'פקודי'
    VAYIKRA = 'ויקרא'
    TZAV = 'צו'
    SHEMINI = 'שמיני'
    TAZRIA = 'תזריע'
    METZORA = 'מצורע'
    ACHAREI_MOS = 'אחרי מות'
    KEDOSHIM = 'קדושים'
    EMOR = 'אמור'
    BEHAR = 'בהר'
    BECHUKOSAI = 'בחוקותי'
    BAMIDBAR = 'במדבר'
    NASSO = 'נשא'
    BEHAALOSCHA = 'בהעלותך'
    SHELACH = 'שלח'
    KORACH = 'קרח'
    CHUKAS = 'חקת'
    BALAK = 'בלק'
    PINCHAS = 'פינחס'
    MATTOS = 'מטות'
    MASEI = 'מסעי'
    DEVARIM = 'דברים'
    VAESCHANAN = 'ואתחנן'
    EIKEV = 'עקב'
    REEH = 'ראה'
    SHOFTIM = 'שופטים'
    KI_SEITZEI = 'כי תצא'
    KI_SAVO = 'כי תבא'
    NITZAVIM = 'נצבים'
    VAYEILECH = 'וילך'
    HAAZINU = 'האזינו'
    VEZOS_HABERACHA = 'וזאת הברכה'


class FourParshios(Enum):
    ZACHOR = 'זכור'
    SHEKALIM = 'שקלים'
    PARAH = 'פרה'
    HACHODESH = 'החודש'


class Days(Enum):
    ROSH_HASHANA = 'ראש השנה'
    YOM_KIPPUR = 'יום כיפור'
    SUCCOS = 'סוכות'
    SHMINI_ATZERES = 'שמיני עצרת'
    SIMCHAS_TORAH = 'שמחת תורה'
    CHANUKA = 'חנוכה'
    TU_BSHVAT = 'ט״ו בשבט'
    PURIM_KATAN = 'פורים קטן'
    PURIM = 'פורים'
    SHUSHAN_PURIM = 'שושן פורים'
    PESACH = 'פסח'
    PESACH_SHENI = 'פסח שני'
    LAG_BAOMER = 'ל״ג בעומר'
    SHAVUOS = 'שבועות'
    TU_BAV = 'ט״ו באב'
    TZOM_GEDALIA = 'צום גדליה'
    TENTH_OF_TEVES = 'י׳ בטבת'
    TAANIS_ESTHER = 'תענית אסתר'
    SEVENTEENTH_OF_TAMMUZ = 'י״ז בתמוז'
    NINTH_OF_AV = 'ט׳ באב'
    ROSH_CHODESH = 'ראש חודש'
    YOM_KIPPUR_KATAN = 'יום כיפור קטן'

